{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
  name: {{ include "kubernetes-event-exporter.serviceAccountName" . }}
  namespace: {{ include "kubernetes-event-exporter.namespace" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
{{- end }}
