{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.serviceMonitor.additionalLabels }}
    {{- end }}
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  namespace: {{ include "kubernetes-event-exporter.namespace" . }}
spec:
  jobLabel: {{ template "kubernetes-event-exporter.fullname" . }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
  selector:
    matchLabels:
      {{- include "kubernetes-event-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
